### ISSUE TITLE
Typo in the readme.

### ISSUE THREAD

**Issue by FaresKi** [mattwar/Kushy#5]
You give this example:
```csp
var loader = new CachedServerSymbolLoader(clusterConnectionString, schemaCacheDirectoryPath);
var db = await loader.LoadDatabaseAsync(dbName);
```
`CachedServerSymbolLoader` does not exist, it's `CachedSymbolLoader`.
I unfortunately spent 15 minutes debugging why the compiler couldn't find the class, it just didn't exist ;)

**Comment by mattwar** [comment]
Sorry about that.  It was originally called CachedServerSymbolLoader, but when I went about cleaning up the project to get it ready to publish, I decided to simplify it.  I even fixed the title in that section of the readme but did not actually fix the example.  It is fixed now.
